### ISSUE TITLE
May 22, 2019 @ 806 Technologies

### ISSUE THREAD

**Issue by samiconductor** [codescooldallas/codescooldallas.github.io#10]

**Comment by pizzachip** [comment]
Present

**Comment by wxb1** [comment]
here

**Comment by gangstead** [comment]
![](https://storage.googleapis.com/cdn.thenewstack.io/media/2018/06/73628d8c-deno-arch-1024x641.jpg)

**Comment by samiconductor** [comment]
17 Meetup RSVPs, 6 headcount there, 4 ITT
