### ISSUE TITLE
September 2019 (2nd to last)

### ISSUE THREAD

**Issue by gangstead** [codescooldallas/codescooldallas.github.io#12]

**Comment by pizzachip** [comment]
Razoyo representin'

**Comment by pizzachip** [comment]
# Download ELM
https://guide.elm-lang.org/install.html
# Install example repo
git clone https://github.com/evancz/elm-architecture-tutorial.git
cd elm-architecture-tutorial
elm reactor

**Comment by gangstead** [comment]
Register and download fusion 360 (it's free)

**Comment by kwandrews7** [comment]
![https://media.giphy.com/media/VelWewgR6CpNK/giphy.gif](https://media.giphy.com/media/VelWewgR6CpNK/giphy.gif)

**Comment by kwandrews7** [comment]
*** Hubot Info ***

Hubot Documentation: https://hubot.github.com/

Hubot Adapters
* https://github.com/slackapi/hubot-slack
* https://github.com/thetimpanist/hubot-discord
* https://github.com/hipchat/hubot-hipchat

Hubot Packages I've Worked On:
* https://github.com/kwandrews7/hubot-rollin
* https://github.com/kwandrews7/hubot-lastfm-notifier
* https://github.com/kwandrews7/hubot-task-countdown
* https://github.com/kwandrews7/hubot-stock-checker
* https://github.com/kwandrews7/hubot-dobermanme
* https://github.com/kwandrews7/hubot-poke
* https://github.com/kwandrews7/hubot-hangman
* https://github.com/kwandrews7/hubot-plusplus-userverify

**Comment by michaeledavis-alto** [comment]
https://giphy.com/gifs/LTFbyWuELIlqlXGLeZ

**Comment by michaeledavis** [comment]
![image](https://user-images.githubusercontent.com/1431628/65649314-ac162b80-dfcb-11e9-9d90-89b401a98c9c.png)
