### ISSUE TITLE
August 15, 2018 Attendance

### ISSUE THREAD

**Issue by michaeledavis** [codescooldallas/codescooldallas.github.io#2]

**Comment by pizzachip** [comment]
![image](https://user-images.githubusercontent.com/12566929/44179787-9216d380-a0be-11e8-9aea-e2fdc2ef2a3c.png)

**Comment by leongaban** [comment]
`(ಠ‿ಠ)`

**Comment by skipper09** [comment]
Hi!

**Comment by smilealdway** [comment]
👍

**Comment by gangstead** [comment]
![](https://i.redd.it/atsdhmg8by811.png)

**Comment by dusteey23** [comment]
here

**Comment by clem-57** [comment]
Cool dudes to have a codes cool in Dallas...Stay cool in the summer sweatshop of North Texas. Whew!

**Comment by kwandrews7** [comment]
👋
