### ISSUE TITLE
September 19, 2018 Attendance

### ISSUE THREAD

**Issue by gangstead** [codescooldallas/codescooldallas.github.io#4]
Python programmers be like:
![image](https://user-images.githubusercontent.com/527760/45727746-9be29980-bb8a-11e8-95f0-9521566712f3.png)

**Comment by mathewdgardner** [comment]
💯

**Comment by aghyad** [comment]
👍

**Comment by pizzachip** [comment]
Present and accounted for
![image](https://user-images.githubusercontent.com/12566929/45788472-5da7b180-bc40-11e8-94c8-a39758872692.png)

**Comment by pettewayshade** [comment]
🙋🏾

**Comment by kwandrews7** [comment]
![https://media0.giphy.com/media/13GIgrGdslD9oQ/giphy.gif](https://media0.giphy.com/media/13GIgrGdslD9oQ/giphy.gif)

**Comment by samiconductor** [comment]
was here

**Comment by gangstead** [comment]
7 ITT, 17 headcount, 35 Meetup RSVPs
