### ISSUE TITLE
November 14, 2018 Attendance

### ISSUE THREAD

**Issue by kwandrews7** [codescooldallas/codescooldallas.github.io#5]
![https://memegenerator.net/img/instances/81296412.jpg](https://memegenerator.net/img/instances/81296412.jpg)

**Comment by gangstead** [comment]
![](https://i.pinimg.com/originals/95/21/77/9521775f96b4c2db8e822513f16c2b48.jpg)

**Comment by jdriver2** [comment]
thanks guys.

**Comment by caseylucas** [comment]
here

**Comment by leblancmeneses** [comment]
present!

some of my cool stuff
https://github.com/leblancmeneses/presentation-raspberrypi-firebase

https://chrome.google.com/webstore/detail/msg/gnmlckdloemhligkocjoakjdmcjbmbbo
