### ISSUE TITLE
January 16, 2019 Attendance

### ISSUE THREAD

**Issue by samiconductor** [codescooldallas/codescooldallas.github.io#8]

**Comment by gangstead** [comment]
![](https://i.pinimg.com/236x/a1/e1/9b/a1e19b90443f51c3818e043a1a355cba--teacher-memes-math-teacher.jpg)

**Comment by pizzachip** [comment]
![image](https://user-images.githubusercontent.com/12566929/51288284-14365b80-19c1-11e9-8e69-e75d6f795014.png)

**Comment by mathewdgardner** [comment]
🌮

**Comment by josejimenezjr0** [comment]
Howdy!

**Comment by SBoscarino** [comment]
Meowdy!

**Comment by clem-57** [comment]
Great place @ Toyota Connect. Thanks Jeff and guys/gals.

**Comment by laurajinks** [comment]
Hi!

**Comment by aghyad** [comment]
🍕 🍕 🍕 👨‍💻

**Comment by andrewwells** [comment]
LGTM

**Comment by genavico** [comment]
HERE!

**Comment by gangstead** [comment]
11 ITT, 23 head count, 68 RSVPs
