### ISSUE TITLE
April 24, 2019 @ Novo Labs

### ISSUE THREAD

**Issue by gangstead** [codescooldallas/codescooldallas.github.io#9]
![image](https://user-images.githubusercontent.com/527760/56686662-1849d780-669a-11e9-9082-eee3e5682af1.png)

**Comment by pizzachip** [comment]
![image](https://user-images.githubusercontent.com/12566929/56700508-43dfb880-66c0-11e9-9e59-40b260c8086b.png)

**Comment by gangstead** [comment]
30 Meetup RSVPs, 18 headcount there, 2 ITT
